environment_group(
  name = "cpus",
  defaults = [":k8"],
  environments = [":k8"])

environment(name = "k8")

constraint_value(
    name = "osx",
    constraint_setting = "@bazel_tools//platforms:os",
)

